export const WILAYA_MAP: Record<number, string> = {
  1: 'Adrar',
  2: 'Chlef',
  3: 'Laghouat',
  4: 'Oum El Bouaghi',
  5: 'Batna',
  6: 'Béjaïa',
  7: 'Biskra',
  8: 'Béchar',
  9: 'Blida',
  10: 'Bouira',
  11: 'Tamanrasset',
  12: 'Tébessa',
  13: 'Tlemcen',
  14: 'Tiaret',
  15: 'Tizi Ouzou',
  16: 'Alger',
  17: 'Djelfa',
  18: 'Jijel',
  19: 'Sétif',
  20: 'Saïda',
  21: 'Skikda',
  22: 'Sidi Bel Abbès',
  23: 'Annaba',
  24: 'Guelma',
  25: 'Constantine',
  26: 'Médéa',
  27: 'Mostaghanem',
  28: 'M\'Sila',
  29: 'Mascara',
  30: 'Ouargla',
  31: 'Oran',
  32: 'El Bayadh',
  33: 'Illizi',
  34: 'Bordj Baji Mokhtar',
  35: 'Boumerdès',
  36: 'El Taref',
  37: 'Tindouf',
  38: 'Tissemsilt',
  39: 'El Oued',
  40: 'Khenchela',
  41: 'Souk Ahras',
  42: 'Tipasa',
  43: 'Mila',
  44: 'Aïn Defla',
  45: 'Naïma',
  46: 'Aïn Témouchent',
  47: 'Ghardaïa',
  48: 'Relizane',
};

export function getWilayaName(code: number | string | null): string {
  if (!code) return 'Non spécifié';
  const numCode = typeof code === 'string' ? parseInt(code, 10) : code;
  return WILAYA_MAP[numCode] || `Code ${numCode}`;
}
